# Mayan Service Registry Configuration
# Nginx-style configuration for heterogeneous building blocks

service dataconsolidation {
    type composition;
    entry_point 192.168.0.164;
    description {
        consolidates data from various data sources
    };
    services {
        data_consolidate {
            order 1;
        }
        detect_duplicates {
            order 2;
            serialized false;
        }
        write {
            order 3;
            serialized true;
        }
    }
}

service dupl_instance_count {
    type simple;
    impl axis2 {
        axa 192.168.0.104;
        axb 192.168.0.105;
        axz 192.168.0.129;
    }
    impl cxf {
        type jaxws_ver_2;
        update true;
        cxa 192.168.0.130;
        cxb 192.168.0.131;
    }
    impl mapreduce_hadoop {
        mra 192.168.0.133;
        mry 192.168.0.157;
    }
    impl hazelcast {
        hza 192.168.0.158;
        hzz 192.168.0.183;
    }
}
